CREATE DATABASE carshop;

CREATE USER carshop WITH PASSWORD 'carshop';

ALTER USER carshop WITH SUPERUSER;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

GRANT ALL PRIVILEGES ON DATABASE carshop TO carshop;
GRANT ALL PRIVILEGES ON SCHEMA public TO carshop;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO carshop;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO carshop;
